Exercicio 5
annecaselato/helpper-origins-sprint-2 pull request #1
Opened 2021-11-06 14:35 UTC by annecaselato

2021-11-06 14:36 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 5](https://trello.com/c/30DI3QmT/197-exerc%C3%ADcio-5)

2021-11-06 15:22 UTC, alanrocha-helpper requested changes

2021-11-06 15:22 UTC, alanrocha-helpper commented on exercicio-5/VowelCounter.ts
> +    static vowels: string = 'aeiou';
Adicionar o marcador de acesso como private, visto que essa variavel não será acessada de fora da classe.
mudar também de static para const, pois esse valor não deve ter a possibilidade de ser alterado.

2021-11-06 15:47 UTC, annecaselato commented on exercicio-5/VowelCounter.ts
> +    static vowels: string = 'aeiou';
Parece que o const não é aceito dentro de classes, eu poderia usar static readonly? Pelo que pesquisei é o que teria o mesmo efeito.

2021-11-08 20:45 UTC, alanrocha-helpper commented on exercicio-5/VowelCounter.ts
> +    static vowels: string = 'aeiou';
Sim

2021-11-08 20:46 UTC, alanrocha-helpper approved these changes

2021-11-09 11:50 UTC, pedro-monteiro-helpper approved these changes

2021-11-09 11:50 UTC, merged