Feature/exercicio 7
annecaselato/helpper-origins-sprint-2 pull request #2
Opened 2021-11-08 01:44 UTC by annecaselato

2021-11-08 01:45 UTC, annecaselato commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 7](https://trello.com/c/i3Xs1GH8/211-exerc%C3%ADcio-7)

2021-11-08 22:50 UTC, alanrocha-helpper requested changes

2021-11-08 22:50 UTC, alanrocha-helpper commented on exercicio-7/FunctionalListInspector.ts
> +//This class receives a list, check if it's numeric, and returns its max, min, and avarage values
Colocar um exemplo de uso, pode ser num console. log mesmo, e chamando a classe pra obter o resultado

2021-11-08 22:50 UTC, alanrocha-helpper commented on exercicio-7/FunctionalListInspector.ts
> +    list : any[];
colocar a propriedade como privada

2021-11-08 22:50 UTC, alanrocha-helpper commented on exercicio-7/ImperativeListInspector.ts
> +    list : any[];
colocar atributo como privado

2021-11-08 22:50 UTC, alanrocha-helpper commented on exercicio-7/ImperativeListInspector.ts
> +//This class receives a list, check if it's numeric, and returns its max, min, and avarage values
Colocar um exemplo de uso, pode ser num console. log mesmo, e chamando a classe pra obter o resultado

2021-11-10 23:15 UTC, alanrocha-helpper approved these changes

2021-11-14 17:36 UTC, merged